// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    AppFooter: typeof import('./src/components/App/Footer.vue')['default']
    AppHeader: typeof import('./src/components/App/Header.vue')['default']
    BaseBreadcrumb: typeof import('./src/components/Base/Breadcrumb.vue')['default']
    BaseCheckbox: typeof import('./src/components/Base/Checkbox.vue')['default']
    BaseIconOutlined: typeof import('./src/components/Base/IconOutlined.vue')['default']
    BaseIconSolid: typeof import('./src/components/Base/IconSolid.vue')['default']
    BaseInput: typeof import('./src/components/Base/Input.vue')['default']
    BaseLinksButton: typeof import('./src/components/Base/LinksButton.vue')['default']
    BaseListbox: typeof import('./src/components/Base/Listbox.vue')['default']
    BaseLogo: typeof import('./src/components/Base/Logo.vue')['default']
    BaseRadio: typeof import('./src/components/Base/Radio.vue')['default']
    BaseRadioGroup: typeof import('./src/components/Base/RadioGroup.vue')['default']
    BaseSelect: typeof import('./src/components/Base/Select.vue')['default']
    BaseSwitch: typeof import('./src/components/Base/Switch.vue')['default']
    FileUpload: typeof import('./src/components/File/Upload.vue')['default']
    FileUploadForm: typeof import('./src/components/File/UploadForm.vue')['default']
    PageHeading: typeof import('./src/components/Page/Heading.vue')['default']
    PageWrapper: typeof import('./src/components/Page/Wrapper.vue')['default']
    SectionWrapper: typeof import('./src/components/Section/Wrapper.vue')['default']
  }
}

export { }
